#![no_std]

// Based on ISO IEC 7816-4

use apdu_app::App as ApduApp;
use apdu_app::Interface;
use core::mem::size_of;
use half::f16;
use libm::scalbnf; // == ldexp
use heapless::Vec;
use heapless::VecView;
use iso7816::aid::App as AidApp;
use iso7816::{command::CommandView, Aid, Status};
use trussed_core::syscall;
use trussed_core::try_syscall;
use trussed_core::types::{KeyId, Mechanism, Location, Message, ShortData, PathBuf, MediumData, StorageAttributes};
use trussed_core::CryptoClient;
use trussed_core::FilesystemClient;

const AES_GCM_NONCE_LEN: usize = 12;
const AES_GCM_TAG_LEN: usize = 16;
const SHA256_LEN: usize = 32;

const MAX_KEYS: usize = 8;
const MAX_KEY_LEN: usize = 10240; // 10Ko

const F32_SIZE: usize = size_of::<f32>();
const F16_SIZE: usize = size_of::<half::f16>();

const QUANTIFICATION_FLOAT16: u8 = 0;
const _QUANTIFICATION_FLOAT32: u8 = 1;

type SkyldKey = Vec<u8, MAX_KEY_LEN>;
type Random = Vec<u8, MAX_KEY_LEN>;

pub struct ProtectedModels {
    activation_key: SkyldKey,
    random: Random,
    quantification: u8,
}

pub struct SkyldApp<C> {
    trussed: C,
    protected_models: Vec<ProtectedModels, MAX_KEYS>,
    buff_reply: SkyldKey, // Because ADPU may not be able to return all the session key in one transfer
}

impl<C> SkyldApp<C> {
    // RID propriétaire 'F0' (see Table 90 in the ISO) suivi de l'identifiant "Skyld"
    const AID: Aid = Aid::new(&[0xF0, 0x53, 0x6B, 0x79, 0x6C, 0x64]);

    pub fn new(trussed: C) -> Self {
        Self {
            trussed,
            protected_models: Vec::new(),
            buff_reply: SkyldKey::new(),
        }
    }
}

// La logique de dérivation est ici
impl<C: CryptoClient + FilesystemClient> SkyldApp<C> {
    fn get_randoms(&mut self, bytes_key_size: usize, quantification: u8, random: &mut Random) -> Result<(), ()> {
        let reply = syscall!(self.trussed.random_bytes(bytes_key_size)); // TRNG
        let raw_random = &reply.bytes[..bytes_key_size];
        
        for chunk in raw_random.chunks_exact(size_of::<u32>()) {
            let mut bits = u32::from_ne_bytes(chunk.try_into().unwrap());
        
            match quantification {
                QUANTIFICATION_FLOAT16 => {
                    let index = bits % 16;
                    let exponent = (index as i32) - 6;
                    
                    let random_val_f32 = scalbnf(1.0, exponent);
                    
                    // Final cast
                    let random_val_f16 = f16::from_f32(random_val_f32);
                    random.extend_from_slice(&random_val_f16.to_ne_bytes()).map_err(|_| ())?;
                }
            
                _ => {
                    let mut random_val_f64: f64; // f64 = double
                    
                    loop {
                        random_val_f64 = (bits as f64 / u32::MAX as f64) * 2.0 - 1.0;
                        
                        if random_val_f64 != 0.0 {
                            break;
                        }
                        
                        let rep = syscall!(self.trussed.random_bytes(4));
                        bits = u32::from_ne_bytes(rep.bytes[..4].try_into().unwrap());
                    }
                
                    // Final cast
                    let random_val_f32 = random_val_f64 as f32;
                    random.extend_from_slice(&random_val_f32.to_ne_bytes()).map_err(|_| ())?;
                }
            }
        }
    
        Ok(())
    }

    fn get_muk(&mut self) -> Result<Message, ()> {
        // muk exists ?
        let muk_path: PathBuf = "skyld_muk".try_into().map_err(|_| ())?;

        let muk_bytes = if let Ok(reply) = try_syscall!(self.trussed.read_file(Location::Internal, muk_path.clone())) {
            reply.data
        } else {
            let new_muk = syscall!(self.trussed.random_bytes(32)).bytes;

            syscall!(self.trussed.write_file(
                Location::Internal,
                muk_path,
                new_muk.clone(),
                None,
            ));

            new_muk
        };

        Ok(muk_bytes)
    }

    // Here we reconstruct the encrypt key based on the hash of the masterKey and the MUK
    fn derive_aes_256_gcm_from_hash(&mut self, hash_kdf: &[u8; SHA256_LEN]) -> Result<KeyId, ()> {
        // Hash as secret shared for KDF
        let base_key_id = syscall!(self.trussed.unsafe_inject_shared_key(
            hash_kdf,
            Location::Volatile,
        )).key;

        let muk_bytes = self.get_muk()?;

        // Prevents that same key can't be generated by another app on the Nitrokey
        let mut context_info = MediumData::new();
        context_info.extend_from_slice(b"skyld-dek-v1:").map_err(|_| ())?;
        context_info.extend_from_slice(&muk_bytes).map_err(|_| ())?;

        let derived_key_id = syscall!(self.trussed.derive_key(
            Mechanism::HmacSha256,
            base_key_id,
            Some(context_info),
            StorageAttributes::new().set_persistence(Location::Volatile),
        )).key;

        // 5. On nettoie la clé de base
        syscall!(self.trussed.delete(base_key_id));

        Ok(derived_key_id)
    }

    fn wrap_data(&mut self, hash_kdf: &[u8; SHA256_LEN], activation_key: &[u8]) -> Result<(), ()> {
        let aes_key_id = self.derive_aes_256_gcm_from_hash(hash_kdf)?;

        let rnd_reply = syscall!(self.trussed.random_bytes(AES_GCM_NONCE_LEN));
        let nonce_bytes = &rnd_reply.bytes[..AES_GCM_NONCE_LEN];
        // TEST : to see if data is correctly wrapped
        // const FIXED_NONCE: [u8; AES_GCM_NONCE_LEN] = [0x42; AES_GCM_NONCE_LEN];
        // let nonce_bytes = &FIXED_NONCE[..];
        let mut nonce = ShortData::new();
        nonce.extend_from_slice(nonce_bytes).map_err(|_| ())?;

        let enc_reply = syscall!(self.trussed.encrypt(
            Mechanism::Aes256Gcm,
            aes_key_id,
            activation_key,
            &[],         // AAD (vide)
            Some(nonce),
        ));

        self.buff_reply.clear();
        self.buff_reply.extend_from_slice(nonce_bytes).map_err(|_| ())?;
        self.buff_reply.extend_from_slice(&enc_reply.ciphertext).map_err(|_| ())?;
        self.buff_reply.extend_from_slice(&enc_reply.tag).map_err(|_| ())?;

        Ok(())
    }

    fn unwrap_data(&mut self, hash_kdf: &[u8; SHA256_LEN], wrapped_activation_key: &[u8], quantification: u8, is_key: u8) -> Result<(), ()> {
        let aes_key_id = self.derive_aes_256_gcm_from_hash(hash_kdf)?;

        // Decrypt key
        // 1. Découpage du Nonce et du Chiffré + Tag
        let nonce = &wrapped_activation_key[..AES_GCM_NONCE_LEN];
        let tag_start = wrapped_activation_key.len() - AES_GCM_TAG_LEN;
        let ciphertext = &wrapped_activation_key[AES_GCM_NONCE_LEN..tag_start];
        let tag = &wrapped_activation_key[tag_start..];

        // 2. Chargement dans un Message Trussed
        let mut msg = Message::new();
        msg.extend_from_slice(ciphertext).map_err(|_| ())?;

        // 3. Appel de déchiffrement authentifié
        let dec_reply = syscall!(self.trussed.decrypt(
            Mechanism::Aes256Gcm,
            aes_key_id,
            &msg,
            &[],   // AAD
            nonce,
            tag,
        ));

        let plaintext = dec_reply.plaintext.ok_or(())?;
        let mut plaintext_bytes = Vec::new();
        plaintext_bytes.extend_from_slice(&plaintext).map_err(|_| ())?; // Vérification automatique du non-débordement

        self.buff_reply.clear();

        if is_key == 1 {
            // Get random
            let mut random = Random::new();
            self.get_randoms(plaintext_bytes.len(), quantification, &mut random)?;

            // Finalize protectedModel
            let protected_model = ProtectedModels { activation_key: plaintext_bytes, random, quantification };
            self.protected_models.push(protected_model).map_err(|_| ())?;
        } else {
            self.buff_reply.extend_from_slice(&plaintext_bytes).map_err(|_| ())?;
        }

        Ok(())
    }

    fn derive_key(activation_key: &[u8], random: &[u8], quantification: u8, out: &mut SkyldKey) -> Result<(), ()> {
        out.clear();

        let quantification_size = match quantification {
            QUANTIFICATION_FLOAT16 => F16_SIZE,
            _ => F32_SIZE,
        };

        let activation_key_iter = activation_key.chunks_exact(F32_SIZE);
        let random_iter = random.chunks_exact(quantification_size);

        //let mut i_usbip = 0;
        for (activation_key_element, random_element) in activation_key_iter.zip(random_iter) {
            //if i_usbip == 13 { break; } // Because USB/IP crashes above, remove when using with true Nitrokey 3
            //i_usbip += 1;
            let activation_key = f32::from_ne_bytes(activation_key_element.try_into().unwrap());

            let val_random = match quantification {
                QUANTIFICATION_FLOAT16 => {
                    let bytes: [u8; F16_SIZE] = random_element.try_into().unwrap();
                    f16::from_bits(u16::from_ne_bytes(bytes)).to_f32()
                },
                _ => {
                    let bytes: [u8; F32_SIZE] = random_element.try_into().unwrap();
                    f32::from_ne_bytes(bytes)
                },
            };
        
            let resultat = activation_key / val_random;
            out.extend_from_slice(&resultat.to_ne_bytes())
                .map_err(|_| ())?;
        }

        Ok(())
    }
}

// 1. Déclaration de l'AID
impl<C> AidApp for SkyldApp<C> {
    fn aid(&self) -> Aid {
        Self::AID
    }
}

// 2. Trait ISO7816 / APDU App
impl<C: CryptoClient + FilesystemClient> ApduApp for SkyldApp<C> {
    // Appelée automatiquement lors de la sélection, pas besoin de faire quelque chose
    fn select(
        &mut self,
        _interface: Interface,
        _apdu: CommandView<'_>,
        _reply: &mut VecView<u8>,
    ) -> Result<(), Status> {
        Ok(())
    }

    fn deselect(&mut self) {}

    fn call(
        &mut self,
        _interface: Interface,
        command: CommandView<'_>,
        reply: &mut VecView<u8>,
    ) -> Result<(), Status> {
        let ins: u8 = command.instruction().into();

        match ins {
            // INS 0x01 : Wrap activation key
            0x01 => {
                let data = command.data();

                let hash_kdf: &[u8; SHA256_LEN] = data[..SHA256_LEN].try_into().unwrap();
                let data_without_hash: &[u8] = data[SHA256_LEN..].try_into().unwrap();

                self.wrap_data(hash_kdf, data_without_hash)
                    .map_err(|_| Status::UnspecifiedCheckingError)?;

                // TODO : deal greater sizes
                let chunk_size = core::cmp::min(reply.capacity(), self.buff_reply.len());

                reply.extend_from_slice(&self.buff_reply[..chunk_size])
                    .map_err(|_| Status::UnspecifiedCheckingError)?;

                Ok(())
            }
            // INS 0x02 : Unwrap activation key
            0x02 => {
                let float_mode: u8 = command.p1;
                let is_key: u8 = command.p2;
                let data = command.data();

                let hash_kdf: &[u8; SHA256_LEN] = data[..SHA256_LEN].try_into().unwrap();
                let data_without_hash: &[u8] = data[SHA256_LEN..].try_into().unwrap();

                self.unwrap_data(hash_kdf, data_without_hash, float_mode, is_key)
                    .map_err(|_| Status::UnspecifiedCheckingError)?;

                Ok(())
            }
            // INS 0x03 : Dérivation de clé
            0x03 => {
                // reply.capacity() = 7 609, donc 7 607 octets libres
                let protected_model_index = command.p1 as usize;

                let protected_model = self
                    .protected_models
                    .get(protected_model_index)
                    .ok_or(Status::NotFound)?;

                Self::derive_key(protected_model.activation_key.as_slice(), protected_model.random.as_slice(), protected_model.quantification, &mut self.buff_reply)
                    .map_err(|_| Status::ConditionsOfUseNotSatisfied)?;

                // We sent the part of the response < reply.capacity()
                // TODO : deal greater sizes
                let chunk_size = core::cmp::min(reply.capacity(), self.buff_reply.len());

                reply.extend_from_slice(&self.buff_reply[..chunk_size])
                    .map_err(|_| Status::UnspecifiedCheckingError)?;

                Ok(())
            }
            _ => Err(Status::InstructionNotSupportedOrInvalid),
        }
    }
}